from __future__ import annotations

BACK_BUTTON = "⬅ Back"
HOME_BUTTON = "🏠 Home"
HABITS_BUTTON = "📋 Habits"
ADD_HABIT_BUTTON = "➕ Add habit"
TIMEZONE_BUTTON = "🕒 Timezone"
STATS_BUTTON = "📊 Stats"
SETTINGS_BUTTON = "⚙️ Settings"
CHOOSE_PERIOD_BUTTON = "📅 Choose period"
DAY_DETAILS_BUTTON = "🔎 Day details"
CUSTOM_SNOOZE_BUTTON = "✍️ Custom"

HOME_TEXT = "Welcome to your habit app.\nChoose a section:"
HABITS_TITLE = "📋 Habits"
SETTINGS_TITLE = "⚙️ Settings"
STATS_TITLE = "📊 Stats"
TIMEZONE_TEXT = "🕒 Timezone\nCurrent: {current}\n\nChoose from list:"
NOTIFICATION_TEXT = "🔔 Notification settings\nCurrent snooze: {current} minutes\nChoose snooze delay:"
NO_HABITS_TEXT = "No habits yet."
NO_HABITS_PLACEHOLDER = "— No habits —"
MY_HABITS_TEXT = "📋 My habits"
HABIT_NOT_FOUND = "Habit not found."
NEW_HABIT_TEXT = "➕ New habit\nSend habit name as text."
NO_HABIT_SELECTED = "No habit selected. Open habit and tap Set time."
SET_REMINDER_TIME_TEXT = "🕒 Set reminder time\nHabit: {title}\nCurrent time: {current}\nSend time in HH:MM format."
TODAY_EMPTY = "✅ Today\nNo active habits."
TODAY_TITLE = "✅ Today"
DONE_SECTION = "✅ Done:"
NOT_DONE_SECTION = "❌ Not done:"
SKIPPED_SECTION = "⏭ Skipped:"
DONE_PROGRESS = "{done} of {total} completed"
CALENDAR_DETAILS_TITLE = "Pick a day for details"
CALENDAR_RANGE_TITLE = "Pick 2 dates for range"
NO_DATA_PERIOD = "No data for this period."
NO_DATA_DAY = "No data for this day."
DATE_NOT_SELECTED = "Date is not selected."
INVALID_DATE = "Invalid date."
CUSTOM_SNOOZE_PROMPT = "Enter snooze delay in minutes (1-240):"

STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
TIME_NOT_SET = "not set"
HABIT_VIEW_TEXT = "🧩 {title}\nStatus: {status}\nTime: {time}"
ACTIVATE_BUTTON = "▶️ Activate"
DEACTIVATE_BUTTON = "⏸ Deactivate"
DELETE_HABIT_BUTTON = "🗑 Delete"
SET_TIME_BUTTON = "⏰ Set time"
CHANGE_TIME_BUTTON = "⏰ Change time"

ERROR_UNKNOWN_ACTION = "Unknown action"
ERROR_INVALID_VALUE = "Invalid value"
ERROR_INVALID_RANGE_VALUE = "Value is out of allowed range"
ERROR_INVALID_HABIT_ID = "Invalid habit id"
ERROR_NO_ACCESS = "Access denied"
ERROR_INVALID_TIMEZONE = "Invalid timezone"
ERROR_INVALID_DATE = "Invalid date"
ERROR_RANGE_TOO_LARGE = "Range is too large. Pick up to 31 days."

ERR_EMPTY_HABIT_NAME = "Habit name cannot be empty."
ERR_LONG_HABIT_NAME = "Too long. Max 140 characters."
ERR_LOST_CONTEXT = "Context is lost. Re-open the habit."
ERR_TIME_FORMAT = "Invalid format. Use HH:MM."
ERR_NO_HABIT_ACCESS = "No access to habit."
ERR_INTEGER_1_240 = "Enter an integer from 1 to 240."
ERR_RANGE_1_240 = "Value must be between 1 and 240 minutes."

SAVED_TEXT = "Saved"
OPENING_APP_TEXT = "Opening app..."
DAILY_SUMMARY_TITLE = "📘 Daily summary"
